config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :passwords => "users/passwords" , :confirmations => "users/confirmations" }
  devise_scope :users do
    get 'signup',  to: 'devise/registrations#new'
    get 'signin',  to: 'devise/sessions#new'
    delete 'signout', to: 'devise/sessions#destroy'
  root "users#index"
  resources :quotations
  resources :tasks
  resources :task_sub_categories
  resources :task_categories
  resources :missions
  resources :main_objects
  resources :object_types
  resources :users
  resources :user_types
  resources :companies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :user
end

app/models/main_object.rb
class MainObject < ApplicationRecord
  belongs_to :object_type
  belongs_to :tenant_or_owner
  belongs_to :pro_in_charge
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :main_object
  belongs_to :user
end

app/models/object_type.rb
class ObjectType < ApplicationRecord
  belongs_to :tenant_or_owner, :class_name => 'user'
  belongs_to :pro_in_charge,  :class_name => 'user'
end

app/models/quotation.rb
class Quotation < ApplicationRecord
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :task_category
  belongs_to :task_sub_category
  belongs_to :mission
  belongs_to :user
end

app/models/task_category.rb
class TaskCategory < ApplicationRecord
end

app/models/task_sub_category.rb
class TaskSubCategory < ApplicationRecord
  belongs_to :task_category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :company
  belongs_to :user_type
  has_many :tenant_or_owner, :class_name => 'main_object', :foreign_key => 'tenant_or_owner'
  has_many :pro_in_charge, :class_name => 'main_object', :foreign_key => 'pro_in_charge'
end

app/models/user_type.rb
class UserType < ApplicationRecord
end

app/controllers/task_categories_controller.rb
class TaskCategoriesController < ApplicationController
  before_action :set_task_category, only: [:show, :edit, :update, :destroy]

  # GET /task_categories
  # GET /task_categories.json
  def index
    @task_categories = TaskCategory.all
  end

  # GET /task_categories/1
  # GET /task_categories/1.json
  def show
  end

  # GET /task_categories/new
  def new
    @task_category = TaskCategory.new
  end

  # GET /task_categories/1/edit
  def edit
  end

  # POST /task_categories
  # POST /task_categories.json
  def create
    @task_category = TaskCategory.new(task_category_params)

    respond_to do |format|
      if @task_category.save
        format.html { redirect_to @task_category, notice: 'Task category was successfully created.' }
        format.json { render :show, status: :created, location: @task_category }
      else
        format.html { render :new }
        format.json { render json: @task_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_categories/1
  # PATCH/PUT /task_categories/1.json
  def update
    respond_to do |format|
      if @task_category.update(task_category_params)
        format.html { redirect_to @task_category, notice: 'Task category was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_category }
      else
        format.html { render :edit }
        format.json { render json: @task_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_categories/1
  # DELETE /task_categories/1.json
  def destroy
    @task_category.destroy
    respond_to do |format|
      format.html { redirect_to task_categories_url, notice: 'Task category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_category
      @task_category = TaskCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_category_params
      params.require(:task_category).permit(:title)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:task_category_id, :task_sub_category_id, :description, :start_date, :finish_date, :deadline_date, :mission_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/main_objects_helper.rb
module MainObjectsHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/object_types_helper.rb
module ObjectTypesHelper
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/helpers/task_categories_helper.rb
module TaskCategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/task_categories/_form.html.erb
<%= form_with(model: task_category, local: true) do |form| %>
  <% if task_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task_category.errors.count, "error") %> prohibited this task_category from being saved:</h2>

      <ul>
      <% task_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/task_categories/edit.html.erb
<h1>Editing Task Category</h1>

<%= render 'form', task_category: @task_category %>

<%= link_to 'Show', @task_category %> |
<%= link_to 'Back', task_categories_path %>

app/views/task_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task Categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_categories.each do |task_category| %>
      <tr>
        <td><%= task_category.title %></td>
        <td><%= link_to 'Show', task_category %></td>
        <td><%= link_to 'Edit', edit_task_category_path(task_category) %></td>
        <td><%= link_to 'Destroy', task_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task Category', new_task_category_path %>

app/views/task_categories/new.html.erb
<h1>New Task Category</h1>

<%= render 'form', task_category: @task_category %>

<%= link_to 'Back', task_categories_path %>

app/views/task_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task_category.title %>
</p>

<%= link_to 'Edit', edit_task_category_path(@task_category) %> |
<%= link_to 'Back', task_categories_path %>